export const FETCH_START = "FETCH_START"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_ERROR = "FETCH_ERROR"

export const MOVIE_START = "MOVIE_START"
export const MOVIE_SUCCESS = "MOVIE_SUCCESS"
export const MOVIE_ERROR = "MOVIE_ERROR"